#!/bin/bash
set -e
set -o pipefail

image=$1
if [ -z "$image" ]; then
  echo >&2 "Usage: crun [image] [command]"
  exit 1
fi
shift

if ! hash docker 2> /dev/null; then
  set -a
  PATH="$PATH:./node_modules/.bin/"
  $@
  exit
fi

if ! docker inspect --format="{{.Id}}" $image > /dev/null; then
  echo "Pulling $image image..."
  docker pull $image
fi

BASH_PATH=$(dirname "${BASH_SOURCE[0]}")
_realpath() {
  if hash realpath 2> /dev/null; then
    realpath $1
  else
    sh -c "cd '$1' && echo \$PWD" #only works with directories, which suffices here
  fi
}
REPO_ROOT=$(_realpath "${BASH_PATH}/../")
CONTAINER_HOME=$REPO_ROOT
STANDARD_PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

SPECIAL_OPTS="--rm"
if [ "$NO_DOCKER_RM" ]; then
  SPECIAL_OPTS=""
fi
DOCKER_SOCK=${DOCKER_SOCK:-/var/run/docker.sock}

set -x
docker run -v $REPO_ROOT:$CONTAINER_HOME -v /tmp:/tmp \
  -v $DOCKER_SOCK:$DOCKER_SOCK \
  --dns "8.8.8.8" \
  -e HOME=$CONTAINER_HOME \
  -w $CONTAINER_HOME \
  -e PATH="./node_modules/.bin/:$STANDARD_PATH" \
  $DOCKER_OPTS $EXTRA_HOST $SPECIAL_OPTS -ti --sig-proxy=true $image "$@"
